# Generated by Django 4.2.7 on 2023-11-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("age", models.IntegerField(null=True)),
                ("games", models.IntegerField(null=True)),
                ("games_started", models.IntegerField(null=True)),
                (
                    "minutes_pg",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "field_goals",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "field_attempts",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "field_percent",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "three_fg",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "three_attempts",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "three_percent",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "two_fg",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "two_attempts",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "two_percent",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "effect_fg_percent",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                ("ft", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("fta", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "ft_percent",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                ("ORB", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("DRB", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("TRB", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("AST", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("STL", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("BLK", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("TOV", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("PF", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("PTS", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("team", models.CharField(default="", max_length=30)),
                ("season", models.IntegerField(null=True)),
            ],
        ),
    ]
