# Generated by Django 4.2.7 on 2023-12-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('player_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('minutes_pg', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('field_goals', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('field_attempts', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('field_percent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('three_fg', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('three_attempts', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('three_percent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('two_fg', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('two_attempts', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('two_percent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('effect_fg_percent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('ft', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ft_attempts', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('ft_percent', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('offensive_rb', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('defensive_rb', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('total_rb', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('assists', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('steals', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('blocks', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('turnovers', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('personal_fouls', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('points', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
                ('player_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
