# Generated by Django 4.2.7 on 2024-02-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerDataTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=255)),
                ("position", models.CharField(default="", max_length=30)),
                ("age", models.IntegerField()),
                ("games", models.IntegerField(blank=True, null=True)),
                ("games_started", models.IntegerField(blank=True, null=True)),
                (
                    "minutes_pg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("field_goals", models.IntegerField(blank=True, null=True)),
                ("field_attempts", models.IntegerField(blank=True, null=True)),
                (
                    "field_percent",
                    models.DecimalField(decimal_places=3, max_digits=4, null=True),
                ),
                ("three_fg", models.IntegerField(blank=True, null=True)),
                ("three_attempts", models.IntegerField(blank=True, null=True)),
                (
                    "three_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("two_fg", models.IntegerField(blank=True, null=True)),
                ("two_attempts", models.IntegerField(blank=True, null=True)),
                (
                    "two_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "effect_fg_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("ft", models.IntegerField(blank=True, null=True)),
                ("ft_attempts", models.IntegerField(blank=True, null=True)),
                (
                    "ft_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("offensive_rb", models.IntegerField(blank=True, null=True)),
                ("defensive_rb", models.IntegerField(blank=True, null=True)),
                ("total_rb", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("steals", models.IntegerField(blank=True, null=True)),
                ("blocks", models.IntegerField(blank=True, null=True)),
                ("turnovers", models.IntegerField(blank=True, null=True)),
                ("personal_fouls", models.IntegerField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(default="", max_length=30)),
                ("season", models.IntegerField(null=True)),
                ("player_id", models.CharField(max_length=255)),
            ],
        ),
    ]
