# Generated by Django 4.2.7 on 2023-11-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0001_initial"),
    ]

    operations = [
        # migrations.AlterModelTable(name="playerdata", table="nba_data_playerdata",),
    ]
