# Generated by Django 4.2.7 on 2023-11-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0002_alter_playerdata_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="playerdata", options={"managed": False},),
    ]
