# Generated by Django 4.2.7 on 2024-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0003_playerdataadvanced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="assist_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="defensive_rb_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="offensive_rb_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="total_rb_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
