# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_alter_playerdata_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playerdata',
            table='nba_data_playerdata',
        ),
    ]
