# Generated by Django 4.2.7 on 2023-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0004_alter_playerdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTotalsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('minutes_played', models.IntegerField(null=True)),
                ('field_goals', models.IntegerField(null=True)),
                ('field_attempts', models.IntegerField(null=True)),
                ('field_percent', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('three_fg', models.IntegerField(null=True)),
                ('three_attempts', models.IntegerField(null=True)),
                ('three_percent', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('two_fg', models.IntegerField(null=True)),
                ('two_attempts', models.IntegerField(null=True)),
                ('two_percent', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('effect_fg_percent', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('ft', models.IntegerField(null=True)),
                ('fta', models.IntegerField(null=True)),
                ('ft_percent', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('ORB', models.IntegerField(null=True)),
                ('DRB', models.IntegerField(null=True)),
                ('TRB', models.IntegerField(null=True)),
                ('AST', models.IntegerField(null=True)),
                ('STL', models.IntegerField(null=True)),
                ('BLK', models.IntegerField(null=True)),
                ('TOV', models.IntegerField(null=True)),
                ('PF', models.IntegerField(null=True)),
                ('PTS', models.IntegerField(null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'nba_data_playertotalsdata',
                'managed': False,
            },
        ),
    ]
