# Generated by Django 4.2.7 on 2024-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0006_alter_playerdataadvanced_box_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="usage_percent",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="vorp",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
