# Generated by Django 4.2.7 on 2024-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0008_alter_playerdataadvanced_block_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="defensive_ws",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="offensive_ws",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerdataadvanced",
            name="win_shares",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
