# Generated by Django 4.2.7 on 2024-02-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphql_api", "0009_alter_playerdataadvanced_defensive_ws_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=50)),
                ("team_abbr", models.CharField(max_length=50)),
                ("season", models.IntegerField()),
                ("league", models.CharField(blank=True, max_length=10)),
                ("wins", models.IntegerField()),
                ("loss", models.IntegerField()),
                (
                    "win_loss_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("finish", models.TextField()),
                (
                    "srs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pace",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "rel_pace",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "ortg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "rel_ortg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "drtg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "rel_drtg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("playoffs", models.TextField()),
                ("coaches", models.TextField()),
                ("top_ws", models.TextField()),
            ],
        ),
    ]
