# Generated by Django 4.2.7 on 2024-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0011_playerdatatotalsplayoffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDataAdvancedPlayoffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('position', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField(blank=True, null=True)),
                ('minutes_played', models.IntegerField(blank=True, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('ts_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('three_p_ar', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ftr', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('offensive_rb_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('defensive_rb_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('total_rb_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('assist_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('steal_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('block_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('turnover_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('usage_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('offensive_ws', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('defensive_ws', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('win_shares', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('win_shares_per', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('offensive_box', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('defensive_box', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('box', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('vorp', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
                ('player_id', models.CharField(max_length=255)),
            ],
        ),
    ]
