# Generated by Django 4.2.7 on 2024-03-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0012_playerdataadvancedplayoffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='top_ws_player',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='ws',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
