# Generated by Django 4.2.11 on 2024-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0013_teamdata_top_ws_player_teamdata_ws'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=255)),
                ('top', models.IntegerField(null=True)),
                ('left', models.IntegerField(null=True)),
                ('date', models.CharField(default='', max_length=255)),
                ('qtr', models.CharField(default='', max_length=255)),
                ('time_remaining', models.CharField(default='', max_length=12)),
                ('result', models.BooleanField(default='', null=True)),
                ('shot_type', models.CharField(default='', max_length=6)),
                ('distance_ft', models.IntegerField(null=True)),
                ('lead', models.BooleanField(null=True)),
                ('lebron_team_score', models.IntegerField(null=True)),
                ('opponent_team_score', models.IntegerField(null=True)),
                ('opponent', models.CharField(default='', max_length=30)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
        ),
    ]
