# Generated by Django 4.2.11 on 2024-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0014_shotchartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotchartdata',
            name='player_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
