# Generated by Django 4.2.11 on 2024-04-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0015_shotchartdata_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shotchartdata',
            old_name='lebron_team_score',
            new_name='team_score',
        ),
    ]
